"""Add subtitle column to Notes

Revision ID: 390e86f9921c
Revises: 
Create Date: 2025-11-26 23:19:46.972089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390e86f9921c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
